# Generated by Django 2.2.7 on 2020-04-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200427_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='profile_pic',
            field=models.ImageField(blank=True, default='userprofile.jpg', null=True, upload_to=''),
        ),
    ]
