# Generated by Django 2.2.7 on 2020-04-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200427_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='profile_pic',
            field=models.ImageField(blank=True, default='userprofile.jpg', null=True, upload_to='profile_pictures'),
        ),
    ]
