# Generated by Django 2.2.7 on 2020-04-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200429_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='profile_pic',
            field=models.ImageField(blank=True, default='../static/images/userprofile.jpg', null=True, upload_to=''),
        ),
    ]
