# Generated by Django 2.2.7 on 2020-05-01 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200429_1732'),
        ('account', '0004_auto_20200501_1440'),
    ]

    operations = [
    ]
