# Generated by Django 2.2.7 on 2019-12-24 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('Supplier_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Supplier_Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'supplier',
            },
        ),
        migrations.CreateModel(
            name='Purchasing',
            fields=[
                ('Purchasing_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PV_No', models.CharField(max_length=20)),
                ('Invoice_No', models.CharField(max_length=20)),
                ('Purchasing_Date', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=100)),
                ('Supplier_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Supplier')),
            ],
            options={
                'db_table': 'purchasing',
            },
        ),
    ]
