# Generated by Django 2.2.7 on 2020-02-12 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'supplier',
            },
        ),
        migrations.CreateModel(
            name='Purchasing',
            fields=[
                ('purchasing_id', models.AutoField(primary_key=True, serialize=False)),
                ('pv_No', models.CharField(max_length=20)),
                ('invoice_no', models.CharField(max_length=20)),
                ('purchasing_date', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Supplier')),
            ],
            options={
                'db_table': 'purchasing',
            },
        ),
    ]
