# Generated by Django 2.2.7 on 2020-02-12 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasing',
            old_name='pv_No',
            new_name='pv_no',
        ),
    ]
