# Generated by Django 2.2.7 on 2019-12-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasing',
            name='Description',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='Description',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='Supplier_Name',
            field=models.CharField(max_length=50),
        ),
    ]
