# Generated by Django 2.2.7 on 2020-04-16 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_model_changes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumables',
            name='category',
        ),
        migrations.RemoveField(
            model_name='fertilizer',
            name='category',
        ),
        migrations.RemoveField(
            model_name='fungicide',
            name='category',
        ),
        migrations.RemoveField(
            model_name='herbicide',
            name='category',
        ),
        migrations.RemoveField(
            model_name='irrigation',
            name='category',
        ),
        migrations.RemoveField(
            model_name='pesticide',
            name='category',
        ),
        migrations.RemoveField(
            model_name='spareparts',
            name='category',
        ),
        migrations.RemoveField(
            model_name='stationery',
            name='category',
        ),
        migrations.RemoveField(
            model_name='surfacetant',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tools',
            name='category',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
