# Generated by Django 2.2.7 on 2019-12-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191224_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasing',
            name='Description',
            field=models.CharField(max_length=100),
        ),
    ]
