# Generated by Django 2.2.7 on 2020-04-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_category_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumables',
            name='threshold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fertilizer',
            name='threshold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fungicide',
            name='threshold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='herbicide',
            name='threshold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='irrigation',
            name='threshold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pesticide',
            name='threshold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='spareparts',
            name='threshold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stationery',
            name='threshold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='surfacetant',
            name='threshold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tools',
            name='threshold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
