# Generated by Django 2.2.7 on 2020-04-26 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_model_threshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='spare_parts_assigned',
        ),
    ]
