# Generated by Django 3.0.3 on 2020-02-12 08:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191224_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('Tool_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Tool_Name', models.CharField(max_length=50)),
                ('Unit_Price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('Quantity', models.PositiveIntegerField(default=0.0)),
                ('Purchasing_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Purchasing')),
            ],
            options={
                'db_table': 'tools',
            },
        ),
        migrations.CreateModel(
            name='Irrigation',
            fields=[
                ('Irrigation_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Irrigation_ItemName', models.CharField(max_length=50)),
                ('Unit_Price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('Quantity', models.PositiveIntegerField(default=0.0)),
                ('Description', models.CharField(max_length=100)),
                ('Purchasing_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Purchasing')),
            ],
            options={
                'db_table': 'irrigation',
            },
        ),
    ]
