# Generated by Django 2.2.7 on 2020-04-26 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_irrigationstaff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IrrigationStaff',
        ),
    ]
