# Generated by Django 2.2.7 on 2020-03-02 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_consumables_fertilizer_fungicide_herbicide_irrigation_pesticide_stationery_surfacetant_tools'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='supplier',
            table='Supplier',
        ),
    ]
