# Generated by Django 2.2.7 on 2020-04-26 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_vehicle_spare_parts_assigned'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='spareparts',
            table='spareparts',
        ),
    ]
