# Generated by Django 2.2.7 on 2020-04-26 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_irrigationstaff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='spare_parts_assigned',
        ),
        migrations.AlterModelTable(
            name='spareparts',
            table='spareparts',
        ),
    ]
