# Generated by Django 2.2.7 on 2020-04-29 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200427_0542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spareparts',
            old_name='spare_parts_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='spareparts',
            old_name='spare_parts_quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='spareparts',
            old_name='spare_parts_unit_price',
            new_name='unit_price',
        ),
    ]
