# Generated by Django 2.2.7 on 2020-03-23 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200305_2213'),
        ('main', '0006_Category_Model'),
    ]

    operations = [
    ]
