# Generated by Django 2.2.7 on 2020-05-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200429_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasing',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='purchasing',
            name='pv_no',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
