# Generated by Django 2.2.7 on 2020-05-02 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200501_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasing',
            name='supplier',
        ),
    ]
