# Generated by Django 2.2.7 on 2020-05-02 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_purchasing_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumables',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Supplier'),
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Supplier'),
        ),
        migrations.AlterField(
            model_name='fungicide',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Supplier'),
        ),
        migrations.AlterField(
            model_name='herbicide',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Supplier'),
        ),
        migrations.AlterField(
            model_name='irrigation',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Supplier'),
        ),
        migrations.AlterField(
            model_name='pesticide',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Supplier'),
        ),
        migrations.AlterField(
            model_name='purchasing',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='vehicle_assigned',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.Vehicle'),
        ),
        migrations.AlterField(
            model_name='stationery',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Supplier'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='description',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='surfacetant',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Supplier'),
        ),
        migrations.AlterField(
            model_name='tools',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Supplier'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_number_plate',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_owner',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
