# Generated by Django 2.2.7 on 2020-05-02 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200502_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumables',
            name='purchasing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Purchasing'),
        ),
        migrations.AlterField(
            model_name='consumables',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Supplier'),
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='purchasing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Purchasing'),
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Supplier'),
        ),
        migrations.AlterField(
            model_name='fungicide',
            name='purchasing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Purchasing'),
        ),
        migrations.AlterField(
            model_name='fungicide',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Supplier'),
        ),
        migrations.AlterField(
            model_name='herbicide',
            name='purchasing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Purchasing'),
        ),
        migrations.AlterField(
            model_name='herbicide',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Supplier'),
        ),
        migrations.AlterField(
            model_name='irrigation',
            name='purchasing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Purchasing'),
        ),
        migrations.AlterField(
            model_name='irrigation',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Supplier'),
        ),
        migrations.AlterField(
            model_name='pesticide',
            name='purchasing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Purchasing'),
        ),
        migrations.AlterField(
            model_name='pesticide',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Supplier'),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='purchasing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Purchasing'),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Supplier'),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='vehicle_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Vehicle'),
        ),
        migrations.AlterField(
            model_name='stationery',
            name='purchasing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Purchasing'),
        ),
        migrations.AlterField(
            model_name='stationery',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Supplier'),
        ),
        migrations.AlterField(
            model_name='surfacetant',
            name='purchasing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Purchasing'),
        ),
        migrations.AlterField(
            model_name='surfacetant',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Supplier'),
        ),
        migrations.AlterField(
            model_name='tools',
            name='purchasing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Purchasing'),
        ),
        migrations.AlterField(
            model_name='tools',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Supplier'),
        ),
    ]
