# Generated by Django 2.2.7 on 2020-05-02 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200502_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrigation',
            name='purchasing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Purchasing'),
        ),
    ]
