# Generated by Django 2.2.7 on 2020-05-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200502_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasing',
            name='pv_no',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(max_length=30),
        ),
    ]
